<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>LoreVcs.Perf</RootNamespace>
    <AssemblyName>repository-dump-perf</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../LoreVcs/LoreVcs.csproj" />
  </ItemGroup>

</Project>
